services:
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_USER=telecom
      - MYSQL_PASSWORD=pass123
      - MYSQL_DATABASE=telecom
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
